services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rodoviaria-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=rodoviaria
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=021204
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rodoviaria-network

  spring-clean-arch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-clean-arch
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=main
    networks:
      - rodoviaria-network
    env_file: .env
networks:
  rodoviaria-network:
    driver: bridge

volumes:
  postgres-data: