services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    # Serviço do RabbitMQ
    rabbitmq:
      image: "rabbitmq:3.13-management"
      container_name: rodoviaria_rabbitmq
      ports:
        - "5672:5672"   # Porta para a aplicação se conectar
        - "15672:15672" # Porta para a interface web de gerenciamento

      # Futuramente, você adicionará sua aplicação e o banco aqui também
